import type { NextPage } from "next"
import Head from "next/head"

import gql from "graphql-tag"
import { useMutation } from "@apollo/client"
import { useRouter } from "next/dist/client/router"

const LoginQuery = gql`
  mutation login($name: String!) {
    login(name: $name) {
      id
      name
    }
  }
`

const Home: NextPage = () => {
  const router = useRouter()
  const [login] = useMutation(LoginQuery)

  const onLogin = async () => {
    const res = await login({ variables: { name: "paul" } })

    console.log(res.data)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <button onClick={onLogin}>login</button>
    </div>
  )
}

export default Home
